version: '3'
services:
  api:
    build: .
    env_file: ./env
    links: 
      - db
    volumes:
      - ./app/:/usr/src/app
    ports: 
      - 8000:8000
  db:
    image: mysql:8.0.16
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rust_api
